### ISSUE TITLE
 table.add_row([satellite['url'], response_parsed['audit']['successCount'], KeyError: 'audit'

### ISSUE THREAD

**Issue by litebito** [konsou/get-storj-audits#1]
Hi

when I try the script, I get the following error:

PS C:\Data\STORJv3\Scripts> python .\get-storj-audits.py localhost:14002
```
AUDIT STATS FOR localhost:14002
Traceback (most recent call last):
  File "C:\Data\STORJv3\Scripts\get-storj-audits.py", line 39, in <module>
    main()
  File "C:\Data\STORJv3\Scripts\get-storj-audits.py", line 28, in main
    table.add_row([satellite['url'], response_parsed['audit']['successCount'],
KeyError: 'audit'
```

I think the keys are different in the output, maybe changed with the latest release?
I could not find a successCount key for the audit key

**Comment by konsou** [comment]
Thanks for the report! The API was changed recently - I'll look into this when I have the time.
